Logistik/Logistik.Web/Controllers/PengirimController.cs
using Logistik.DAL;
using Logistik.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Logistik.Web.Controllers
{
    public class PengirimController : Controller
    {
        // GET: Pengirim
        public ActionResult Index()
        {
            List<PengirimViewModel> list = PengirimDAL.Get();
            return View(list);
        }

        public ActionResult List()
        {
            List<PengirimViewModel> list = PengirimDAL.Get();
            return PartialView("_List", list);
        }

        public ActionResult TambahKota()
        {
            return PartialView("_TambahKota");
        }

        public ActionResult PilihKota()
        {
            List<KotaViewModel> kota = KotaDAL.Get();
            return PartialView("_PilihKota", kota);
        }

        public ActionResult Insert()
        {
            return PartialView("_Insert");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Insert(PengirimViewModel model)
        {
            if (ModelState.IsValid && PengirimDAL.Add(model))
            {
                var result = new { message = "success" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else if (ModelState.IsValid && PengirimDAL.AddExistingKota(model))
            {
                var result = new { message = "success" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return PartialView("_Insert");
        }

        public ActionResult Detail(int id)
        {
            PengirimViewModel pengirim = PengirimDAL.Get(id);
            return PartialView("_Detail", pengirim);
        }

        public ActionResult Edit(int id)
        {
            PengirimViewModel pengirim = PengirimDAL.Get(id);
            return PartialView("_Edit", pengirim);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PengirimViewModel model)
        {
            if (ModelState.IsValid && PengirimDAL.Edit(model))
            {
                var result = new { message = "success" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return PartialView("_Edit");
        }

        public ActionResult Delete(int id)
        {
            PengirimViewModel pengirim = PengirimDAL.Get(id);
            return PartialView("_Delete", pengirim);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(PengirimViewModel model)
        {
            if (ModelState.IsValid && PengirimDAL.Delete(model))
            {
                var result = new { message = "success" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return PartialView("_Delete");
        }
    }
}

Logistik/Logistik.Web/Views/Pengirim/Index.cshtml
@model IEnumerable<Logistik.ViewModel.PengirimViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="box">
    <div class="box-header">
        <h3 class="box-title">Data Pengirim</h3>
        <div class="box-tools">
            <a class="btn btn-primary btn-sm" id="btn-add" title="Create New Data"><i class="fa fa-plus"></i></a>
        </div>
    </div>
    <div class="box-body">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Nama Pengirim</th>
                    <th>Kota</th>
                    <th>Kode Pos</th>
                    <th>Contact</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <tbody id="list-data">
                @Html.Partial("_List", Model)
            </tbody>
        </table>
    </div>
</div>

<div class="modal fade" id="modal-input">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Default Modal</h4>
            </div>
            <div class="modal-body">

            </div>
        </div>
    </div>
</div>

@section Scripts{
<script>
        function loadData() {
            $.ajax({
                url: '@Url.Action("List","Pengirim")',
                type: 'get',
                dataType: 'html',
                success: function (data) {
                    $("#list-data").html(data);
                }
            });
            return false;
        };

        $("#btn-add").click(function () {
            $.ajax({
                url: '@Url.Action("Insert","Pengirim")',
                type: 'get',
                dataType: 'html',
                success: function (data) {
                    $("#modal-input").find(".modal-title").html("Tambah Data Pengirim Baru");
                    $("#modal-input").find(".modal-body").html(data);
                    $("#modal-input").modal("show");
                }
            });
            return false;
        });

        $("#modal-input").on("click", ".radio-kota1", function (data) {
            $.ajax({
                url: '@Url.Action("PilihKota","Pengirim")',
                type: 'get',
                dataType: 'html',
                success: function (data) {
                    $("#modal-input").find("#data-kota").html(data);
                }
            });
            return false;
        });

        $("#modal-input").on("click", ".radio-kota2", function (data) {
            $.ajax({
                url: '@Url.Action("TambahKota","Pengirim")',
                type: 'get',
                dataType: 'html',
                success: function (data) {
                    $("#modal-input").find("#data-kota").html(data);
                }
            });
            return false;
        });

        $("#list-data").on("click", ".detail", function () {
            var vId = $(this).val();
            $.ajax({
                url: '@Url.Action("Detail","Pengirim")',
                type: 'get',
                dataType: 'html',
                data: { id: vId },
                success: function (data) {
                    $("#modal-input").find(".modal-title").html("Detail Data Pengirim");
                    $("#modal-input").find(".modal-body").html(data);
                    $("#modal-input").modal("show");
                }
            });
            return false;
        });

        $("#list-data").on("click", ".edit", function () {
            var vId = $(this).val();
            $.ajax({
                url: '@Url.Action("Edit","Pengirim")',
                type: 'get',
                dataType: 'html',
                data: { id: vId },
                success: function (data) {
                    $("#modal-input").find(".modal-title").html("Edit Data Pengirim");
                    $("#modal-input").find(".modal-body").html(data);
                    $("#modal-input").modal("show");
                }
            });
            return false;
        });

        $("#list-data").on("click", ".delete", function () {
            var vId = $(this).val();
            $.ajax({
                url: '@Url.Action("Delete","Pengirim")',
                type: 'get',
                dataType: 'html',
                data: { id: vId },
                success: function (data) {
                    $("#modal-input").find(".modal-title").html("Detail Data Pengirim");
                    $("#modal-input").find(".modal-body").html(data);
                    $("#modal-input").modal("show");
                }
            });
            return false;
        });

        $("#modal-input").on("submit", "#form-pengirim", function () {
            $.ajax({
                url: $(this).attr('action'),
                type: $(this).attr('method'),
                dataType: 'json',
                data: $(this).serialize(),
                success: function (data) {
                    if (data.message == 'success') {
                        $("#modal-input").modal("hide");
                        loadData();
                    } else {
                        $("#modal-input").find(".modal-body").html(data);
                    }
                }
            });
            return false;
        });
</script>
}

Logistik/Logistik.Web/Views/Pengirim/_Delete.cshtml
@model Logistik.ViewModel.PengirimViewModel

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "form-pengirim", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x => x.Id)

    <p>Are you sure want to delete this&hellip;?</p>

    <div class="row col-md-offset-3">
        <div class="col-md-5">
            <label>Nama Pengirim</label>
        </div>
        @Html.DisplayFor(x => x.NamaPengirim)
    </div>

    <div class="row col-md-offset-3">
        <div class="col-md-5">
            <label>Kota Asal</label>
        </div>
        @Html.DisplayFor(x => x.NamaKota)
    </div>

    <div class="row col-md-offset-3">
        <div class="col-md-5">
            <label>Kode Pos</label>
        </div>
        @Html.DisplayFor(x => x.KodePos)
    </div>

    <div class="row col-md-offset-3">
        <div class="col-md-5">
            <label>Contact</label>
        </div>
        @Html.DisplayFor(x => x.NoTelp)
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-danger">Delete</button>
    </div>
}

Logistik/Logistik.Web/Views/Pengirim/_Detail.cshtml
@model Logistik.ViewModel.PengirimViewModel

<div class="row col-md-offset-3">
    <div class="col-md-5">
        <label>Nama Pengirim</label>
    </div>
    @Html.DisplayFor(x => x.NamaPengirim)
</div>

<div class="row col-md-offset-3">
    <div class="col-md-5">
        <label>Kota Asal</label>
    </div>
    @Html.DisplayFor(x => x.NamaKota)
</div>

<div class="row col-md-offset-3">
    <div class="col-md-5">
        <label>Kode Pos</label>
    </div>
    @Html.DisplayFor(x => x.KodePos)
</div>

<div class="row col-md-offset-3">
    <div class="col-md-5">
        <label>Contact</label>
    </div>
    @Html.DisplayFor(x => x.NoTelp)
</div>

Logistik/Logistik.Web/Views/Pengirim/_Edit.cshtml
@model Logistik.ViewModel.PengirimViewModel

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "form-pengirim", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(x => x.Id)
    @Html.HiddenFor(x => x.KotaAsalId)

    <div class="form-group">
        <label class="control-label col-md-4">Nama Pengirim</label>
        <div class="col-md-8">
            @Html.EditorFor(x => x.NamaPengirim, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(x => x.NamaPengirim, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-4">Kode Pos</label>
        <div class="col-md-8">
            @Html.EditorFor(x => x.KodePos, new { htmlAttributes = new { @class = "form-control", @max = "5" } })
            @Html.ValidationMessageFor(x => x.KodePos, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-4">Contact</label>
        <div class="col-md-8">
            @Html.EditorFor(x => x.NoTelp, new { htmlAttributes = new { @class = "form-control", @max = "12" } })
            @Html.ValidationMessageFor(x => x.NoTelp, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="modal-footer">
        <button type="reset" class="btn btn-default pull-left">Reset</button>
        <button type="submit" class="btn btn-success">Save</button>
    </div>
}

Logistik/Logistik.Web/Views/Pengirim/_Insert.cshtml
@model Logistik.ViewModel.PengirimViewModel

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "form-pengirim", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <label class="control-label col-md-4">Nama Pengirim</label>
        <div class="col-md-8">
            <input type="text" name="NamaPengirim" class="form-control" />
            @Html.ValidationMessageFor(x => x.NamaPengirim, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-4"></label>
        <div class="col-md-8">
            <input type="radio" class="radio-kota1" id="radio-kota" name="radio-kota" value="1" /> Pilih Kota
            <input type="radio" class="radio-kota2" id="radio-kota" name="radio-kota" value="2" /> Tambah Kota Baru
        </div>
    </div>

    <div id="data-kota">

    </div>

    <div class="form-group">
        <label class="control-label col-md-4">Kode Pos</label>
        <div class="col-md-8">
            <input type="text" name="KodePos" class="form-control" />
            @Html.ValidationMessageFor(x => x.KodePos, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-4">Contact</label>
        <div class="col-md-8">
            <input type="text" name="NoTelp" class="form-control" />
            @Html.ValidationMessageFor(x => x.NoTelp, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="modal-footer">
        <button type="reset" class="btn btn-default pull-left">Reset</button>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
}

Logistik/Logistik.Web/Views/Pengirim/_List.cshtml
@model IEnumerable<Logistik.ViewModel.PengirimViewModel>
@foreach (var item in Model)
{
    <tr>
        <td>@Html.DisplayFor(x => item.NamaPengirim)</td>
        <td>@Html.DisplayFor(x => item.NamaKota)</td>
        <td>@Html.DisplayFor(x => item.KodePos)</td>
        <td>@Html.DisplayFor(x => item.NoTelp)</td>
        <td align="center" class="col-md-2">
            <button type="button" class="btn btn-warning btn-xs detail" title="Detail" value="@item.Id"><i class="glyphicon glyphicon-eye-open"></i></button>
            <button type="button" class="btn btn-success btn-xs edit" title="Edit" value="@item.Id"><i class="glyphicon glyphicon-edit"></i></button>
            <button type="button" class="btn btn-danger btn-xs delete" title="Delete" value="@item.Id"><i class="glyphicon glyphicon-trash"></i></button>
        </td>
    </tr>
}

Logistik/Logistik.Web/Views/Pengirim/_PilihKota.cshtml
@model IEnumerable<Logistik.ViewModel.KotaViewModel>

<div class="form-group">
    <label class="control-label col-md-4">Kota</label>
    <div class="col-md-8">
        <select class="form-control" id="select-kota" name="KotaAsalId">
            <option>Pilih Kota</option>
            @foreach (var item in Model)
            {
                <option value="@item.Id">@item.NamaKota</option>
            }
        </select>
    </div>
</div>

Logistik/Logistik.Web/Views/Pengirim/_TambahKota.cshtml
@model Logistik.ViewModel.PengirimViewModel

<div class="form-group">
    <label class="control-label col-md-4">Kota</label>
    <div class="col-md-8">
        <input type="text" name="NamaKota" class="form-control" />
        @Html.ValidationMessageFor(x => x.NamaKota, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    <label class="control-label col-md-4">Harga</label>
    <div class="col-md-8">
        <input type="number" name="Harga" class="form-control" min="15000" step="5000" />
        @Html.ValidationMessageFor(x => x.Harga, "", new { @class = "text-danger" })
    </div>
</div>