Logistik/Logistik.Web/Controllers/JenisPengirimanController.cs
using Logistik.DAL;
using Logistik.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Logistik.Web.Controllers
{
    public class JenisPengirimanController : Controller
    {
        // GET: JenisPengiriman
        public ActionResult Index()
        {
            List<JenisPengirimanViewModel> list = JenisPengirimanDAL.Get();
            return View(list);
        }

        public ActionResult Detail(int id)
        {
            JenisPengirimanViewModel model = JenisPengirimanDAL.Get(id);
            return PartialView("_Detail", model);
        }

        public ActionResult List()
        {
            List<JenisPengirimanViewModel> model = JenisPengirimanDAL.Get();
            return PartialView("_List", model);
        }

        public ActionResult Insert()
        {
            return PartialView("_Insert");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Insert(JenisPengirimanViewModel model)
        {
            if (ModelState.IsValid && JenisPengirimanDAL.Insert(model))
            {
                var result = new { message = "success" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return PartialView("_Insert");
        }

        public ActionResult Edit(int id)
        {
            JenisPengirimanViewModel model = JenisPengirimanDAL.Get(id);
            return PartialView("_Edit", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(JenisPengirimanViewModel model)
        {
            if (ModelState.IsValid && JenisPengirimanDAL.Edit(model))
            {
                var result = new { message = "success" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return PartialView("_Edit");
        }

        public ActionResult Delete(int id)
        {
            JenisPengirimanViewModel model = JenisPengirimanDAL.Get(id);
            return PartialView("_Delete", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(JenisPengirimanViewModel model)
        {
            if (ModelState.IsValid && JenisPengirimanDAL.Delete(model))
            {
                var result = new { message = "success" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return PartialView("_Delete");
        }
    }
}

Logistik/Logistik.Web/Views/JenisPengiriman/Index.cshtml
@model IEnumerable<Logistik.ViewModel.JenisPengirimanViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="box">
    <div class="box-header">
        <h3 class="box-title">Data Jenis Pengiriman</h3>
        <div class="box-tools">
            <a class="btn btn-primary btn-sm" id="btn-add" title="Create New Data"><i class="fa fa-plus"></i></a>
        </div>
    </div>
    <div class="box-body">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Jenis Pengiriman</th>
                    <th>Harga</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <tbody id="list-data">
                @Html.Partial("_List", Model)
            </tbody>
        </table>
    </div>
</div>

<div class="modal fade" id="modal-input">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Default Modal</h4>
            </div>
            <div class="modal-body">

            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        function loadData() {
            $.ajax({
                url: '@Url.Action("List","JenisPengiriman")',
                type: 'get',
                dataType: 'html',
                success: function (data) {
                    $("#list-data").html(data);
                }
            });
        };

        $("#btn-add").click(function () {
            $.ajax({
                url: '@Url.Action("Insert","JenisPengiriman")',
                type: 'get',
                dataType: 'html',
                success: function (data) {
                    $("#modal-input").find(".modal-title").html("Tambah Jenis Pengiriman Baru");
                    $("#modal-input").find(".modal-body").html(data);
                    $("#modal-input").modal("show");
                }
            });
            return false;
        });

        $("#list-data").on("click", ".detail", function () {
            var vId = $(this).val();
            $.ajax({
                url: '@Url.Action("Detail","JenisPengiriman")',
                type: 'get',
                data: { id: vId },
                dataType: 'html',
                success: function (data) {
                    $("#modal-input").find(".modal-title").html("Detail Jenis Pengiriman");
                    $("#modal-input").find(".modal-body").html(data);
                    $("#modal-input").modal("show");
                }
            });
            return false;
        });

        $("#list-data").on("click", ".edit", function () {
            var vId = $(this).val();
            $.ajax({
                url: '@Url.Action("Edit","JenisPengiriman")',
                type: 'get',
                data: { id: vId },
                dataType: 'html',
                success: function (data) {
                    $("#modal-input").find(".modal-title").html("Edit Jenis Pengiriman");
                    $("#modal-input").find(".modal-body").html(data);
                    $("#modal-input").modal("show");
                }
            });
            return false;
        });

        $("#list-data").on("click", ".delete", function () {
            var vId = $(this).val();
            $.ajax({
                url: '@Url.Action("Delete","JenisPengiriman")',
                type: 'get',
                data: { id: vId },
                dataType: 'html',
                success: function (data) {
                    $("#modal-input").find(".modal-title").html("Delete Jenis Pengiriman");
                    $("#modal-input").find(".modal-body").html(data);
                    $("#modal-input").modal("show");
                }
            });
            return false;
        });

        $("#modal-input").on("submit", "#form-jenis-pengiriman", function () {
            $.ajax({
                url: $(this).attr('action'),
                type: $(this).attr('method'),
                dataType: 'json',
                data: $(this).serialize(),
                success: function (data) {
                    if (data.message == "success") {
                        $("#modal-input").modal("hide");
                        loadData();
                    } else {
                        $("#modal-input").find("#modal-body").html(data);
                    }
                }
            });
            return false;
        });
    </script>
}

Logistik/Logistik.Web/Views/JenisPengiriman/_Delete.cshtml
@model Logistik.ViewModel.JenisPengirimanViewModel

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "form-jenis-pengiriman", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x => x.Id)

    <p>Are you sure want to delete this&hellip;?</p>

    <div class="row col-md-offset-3">
        <div class="col-md-5">
            <label>Jenis Pengiriman</label>
        </div>
        @Html.DisplayFor(x => x.Nama)
    </div>
    <div class="row col-md-offset-3">
        <div class="col-md-5">
            <label>Harga</label>
        </div>
        @Html.DisplayFor(x => x.Harga)
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-danger">Delete</button>
    </div>
}

Logistik/Logistik.Web/Views/JenisPengiriman/_Detail.cshtml
@model Logistik.ViewModel.JenisPengirimanViewModel

<div class="row col-md-offset-3">
    <div class="col-md-5">
        <label>Jenis Pengiriman</label>
    </div>
    @Html.DisplayFor(x => x.Nama)
</div>
<div class="row col-md-offset-3">
    <div class="col-md-5">
        <label>Harga</label>
    </div>
    @Html.DisplayFor(x => x.Harga)
</div>

Logistik/Logistik.Web/Views/JenisPengiriman/_Edit.cshtml
@model Logistik.ViewModel.JenisPengirimanViewModel

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "form-jenis-pengiriman", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(x => x.Id)

    <div class="form-group">
        <label class="control-label col-md-4">Jenis Pengiriman</label>
        <div class="col-md-8">
            @Html.EditorFor(x => x.Nama, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(x => x.Nama, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Harga, new { @class = "control-label col-md-4" })
        <div class="col-md-8">
            @Html.EditorFor(x => x.Harga, new { htmlAttributes = new { @class = "form-control", @type = "number", @step = "5000" } })
            @Html.ValidationMessageFor(x => x.Harga, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="modal-footer">
        <button type="reset" class="btn btn-default pull-left">Reset</button>
        <button type="submit" class="btn btn-success">Save</button>
    </div>
}

Logistik/Logistik.Web/Views/JenisPengiriman/_Insert.cshtml
@model Logistik.ViewModel.JenisPengirimanViewModel

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "form-jenis-pengiriman", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <label class="control-label col-md-4">Jenis Pengiriman</label>
        <div class="col-md-8">
            <input type="text" name="Nama" class="form-control" />
            @Html.ValidationMessageFor(x => x.Nama, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-4">Harga</label>
        <div class="col-md-8">
            <input type="number" name="Harga" class="form-control" min="5000" step="5000" />
            @Html.ValidationMessageFor(x => x.Harga, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="modal-footer">
        <button type="reset" class="btn btn-default pull-left">Reset</button>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
}

Logistik/Logistik.Web/Views/JenisPengiriman/_List.cshtml
@model IEnumerable<Logistik.ViewModel.JenisPengirimanViewModel>
@foreach (var item in Model)
{
    <tr>
        <td>@Html.DisplayFor(x => item.Nama)</td>
        <td>@Html.DisplayFor(x => item.Harga)</td>
        <td align="center" class="col-md-2">
            <button type="button" class="btn btn-warning btn-xs detail" title="Detail" value="@item.Id"><i class="glyphicon glyphicon-eye-open"></i></button>
            <button type="button" class="btn btn-success btn-xs edit" title="Edit" value="@item.Id"><i class="glyphicon glyphicon-edit"></i></button>
            <button type="button" class="btn btn-danger btn-xs delete" title="Delete" value="@item.Id"><i class="glyphicon glyphicon-trash"></i></button>
        </td>
    </tr>
}