Logistik/Logistik.Web/Controllers/KendaraanController.cs
using System;
using Logistik.ViewModel;
using Logistik.DAL;
using Logistik.Model;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Logistik.Web.Controllers
{
    public class KendaraanController : Controller
    {
        // GET: Kendaraan
        public ActionResult Index()
        {
            List<KendaraanViewModel> list = KendaraanDAL.Get();
            return View(KendaraanDAL.Get());
        }

        public ActionResult List()
        {
            List<KendaraanViewModel> model = KendaraanDAL.Get();
            return PartialView("_List",model);
        }

        public ActionResult Detail(int id)
        {
            KendaraanViewModel model = KendaraanDAL.Get(id);
            return PartialView("_Detail", model);
        }

        public ActionResult Add()
        {
            return PartialView("_Add");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(KendaraanViewModel model)
        {
            if (ModelState.IsValid&&KendaraanDAL.InsertData(model))
            {
                var result=new {message="success" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return PartialView("_Add");
        }

        public ActionResult Edit(int id)
        {
            KendaraanViewModel model = KendaraanDAL.Get(id);
            return PartialView("_Edit",model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(KendaraanViewModel model)
        {
            if (ModelState.IsValid&&KendaraanDAL.UpdateData(model))
            {
                var result = new { message = "success" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return PartialView("_Edit");
        }

        public ActionResult Delete(int id)
        {
            KendaraanViewModel model = KendaraanDAL.Get(id);
            return PartialView("_Delete",model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(KendaraanViewModel model)
        {
            if (ModelState.IsValid&&KendaraanDAL.DeleteData(model))
            {
                var result = new { message = "success" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return PartialView("_Delete");
        }
    }
}

Logistik/Logistik.Web/Views/Kendaraan/Index.cshtml
@model IEnumerable<Logistik.ViewModel.KendaraanViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="box box-primary">
    <div class="box-header">
        <h3 class="box-title">Data Kendaraan</h3>
        <div class="box-tools">
            <button class="btn btn-primary btn-sm" id="btn-add"><i class="fa fa-plus"></i></button>
        </div>
    </div>
    <div class="box-body no-padding">
        <table class="table table-bordered table-hover table-responsive table-striped">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(x=>x.Merk)</th>
                    <th>@Html.DisplayNameFor(x=>x.NoPol)</th>
                    <th>@Html.DisplayNameFor(x=>x.Status)</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <tbody id="list-data">
                @Html.Partial("_List",Model)
            </tbody>
        </table>
    </div>
</div>

<div class="modal fade" id="modal-input">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Default Modal</h4>
            </div>
            <div class="modal-body">

            </div>
        </div>
    </div>
</div>
@section Scripts
    {
        <script>
            function loadData()
            {
                $.ajax(
                    {
                        url:'@Url.Action("List","Kendaraan")',
                        type:'get',
                        dataType:'html',
                        success: function (data)
                        {
                            $("#list-data").html(data);
                        }
                    });
                return false;
            };
            $("#btn-add").click(function ()
            {
                $.ajax(
                    {
                        url:'@Url.Action("Add","Kendaraan")',
                        type:'get',
                        dataType:'html',
                        success: function (data)
                        {
                            $("#modal-input").find(".modal-title").html("Add Data Kendaraan");
                            $("#modal-input").find(".modal-body").html(data);
                            $("#modal-input").modal("show");
                        }
                    });
                return false;
            });
            $("#list-data").on("click", ".detail", function ()
            {
                var vId = $(this).val();
                $.ajax(
                    {
                        url: '@Url.Action("Detail","Kendaraan")',
                        type: 'get',
                        data: { id: vId },
                        dataType:'html',
                        success: function (data)
                        {
                            $("#modal-input").find(".modal-title").html("Detail Data Kendaraan");
                            $("#modal-input").find(".modal-body").html(data);
                            $("#modal-input").modal("show");
                        }
                    });
                return false;
            });

            $("#list-data").on("click", ".edit", function ()
            {
                var vId = $(this).val();
                $.ajax(
                    {
                        url:'@Url.Action("Edit","Kendaraan")',
                        type: 'get',
                        data: { id: vId },
                        dataType:'html',
                        success: function (data)
                        {
                            $("#modal-input").find(".modal-title").html("Edit Data Kendaraan");
                            $("#modal-input").find(".modal-body").html(data);
                            $("#modal-input").modal("show");
                        }

                    });
                return false;
            });
            $("#list-data").on("click", ".delete", function ()
            {
                var vId = $(this).val();
                $.ajax(
                    {
                        url:'@Url.Action("Delete","Kendaraan")',
                        type: 'get',
                        data: { id: vId },
                        dataType:'html',
                        success: function (data)
                        {
                            $("#modal-input").find(".modal-title").html("Delete Data");
                            $("#modal-input").find(".modal-body").html(data);
                            $("#modal-input").modal("show");
                        }
                    });
                return false;
            });

            $("#modal-input").on("submit", "#form-kendaraan", function ()
            {
                $.ajax(
                    {
                        url: $(this).attr('action'),
                        type: $(this).attr('method'),
                        dataType: 'json',
                        data: $(this).serialize(),
                        success: function (data)
                        {
                            if (data.message == 'success') {
                                $("#modal-input").modal("hide");
                                loadData();
                            }
                            else
                            {
                                $("#modal-input").find(".modal-body").html(data);
                            }
                        }

                    });
                return false;
            });
        </script>
    }

Logistik/Logistik.Web/Views/Kendaraan/_Add.cshtml
@model Logistik.ViewModel.KendaraanViewModel
@using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal", @id = "form-kendaraan" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    
    <div class="form-group">
        @Html.LabelFor(x => x.Merk, new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            @Html.TextBoxFor(m => m.Merk, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Merk, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.NoPol, new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            @Html.TextBoxFor(m => m.NoPol, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.NoPol, "", new { @class = "text-danger" })
        </div>
    </div>
    
        

        <div class="form-group">
            @Html.LabelFor(x => x.Status, new { @class = "col-md-3 text-right" })
            <div class="col-md-9">
                @Html.RadioButtonFor(x => x.Status, "Available", new { @class = "Radio-inline" })Available
                @Html.RadioButtonFor(x => x.Status, "On The Road", new { @class = "Radio-inline" })On The Road
            </div>
        </div>



        <div class="modal-footer">
            <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary pull-right">Submit</button>
        </div>

}

Logistik/Logistik.Web/Views/Kendaraan/_Delete.cshtml
@model Logistik.ViewModel.KendaraanViewModel
    @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal", @id = "form-kendaraan" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x=>x.Id)

        <p>Are you sure to delete this&hellip;?</p>

        <div class="row col-md-offset-3">
            <div class="col-md-5">
                <label>Merek Kendaraan</label>
            </div>
            @Html.DisplayFor(x=>x.Merk)
        </div>

        <div class="row col-md-offset-3">
            <div class="col-md-5">
                <label>Nomor Polisi</label>
            </div>
            @Html.DisplayFor(x=>x.NoPol)
        </div>

        <div class="row col-md-offset-3">
            <div class="col-md-5">
                <label>Status</label>
            </div>
            @Html.DisplayFor(x=>x.Status)
        </div>

        <div class="modal-footer">
            <button type="submit" class="btn btn-danger pull-right">Delete</button>
            <button type="button"class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
        </div>
    }

Logistik/Logistik.Web/Views/Kendaraan/_Detail.cshtml
@model Logistik.ViewModel.KendaraanViewModel
    
        <div class="row col-md-offset-3">
            <div class="col-md-5">
            <label>Merek Kendaraan</label>
            </div>
            @Html.DisplayFor(x=>x.Merk)
        </div>
        <div class="row col-md-offset-3">
            <div class="col-md-5">
                <label>Nomor Polisi</label>
            </div>
            @Html.DisplayFor(x=>x.NoPol)
        </div>
        <div class="row col-md-offset-3">
            <div class="col-md-5">
                <label>Status</label>
            </div>
            @Html.DisplayFor(x=>x.Status)
        </div>

    

Logistik/Logistik.Web/Views/Kendaraan/_Edit.cshtml
@model Logistik.ViewModel.KendaraanViewModel
    @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal", @id = "form-kendaraan" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true,"",new {@class="text-danger" })
        @Html.HiddenFor(x=>x.Id)

        <div class="form-group">
            @Html.LabelFor(x=>x.Merk,new {@class="col-md-3 control-label" })
            <div class="col-md-9">
                @Html.TextBoxFor(m=>m.Merk,new {@class="form-control" })
                @Html.ValidationMessageFor(x=>x.Merk,"",new {@class="text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(x=>x.NoPol,new {@class="control-label col-md-3" })
            <div class="col-md-9">
                @Html.TextBoxFor(m=>m.NoPol,new {@class="form-control" })
                @Html.ValidationMessageFor(x=>x.NoPol,"",new {@class="text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(x=>x.Status,new {@class="control-label col-md-3 text-right" })
            <div class="col-md-9">
                @Html.RadioButtonFor(x=>x.Status,"Available",new {@class="radio-inline" })Available
                @Html.RadioButtonFor(x=>x.Status,"On The Road",new {@class="radio-inline" })On The Road
            </div>
        </div>

        <div class="modal-footer">
            <button type="reset"class="btn btn-default pull-left">Reset</button>
            <button type="submit" class="btn btn-success pull-right">Save</button>
        </div>
    }

Logistik/Logistik.Web/Views/Kendaraan/_List.cshtml
@model IEnumerable<Logistik.ViewModel.KendaraanViewModel>
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem=>item.Merk)</td>
            <td>@Html.DisplayFor(modelItem=>item.NoPol)</td>
            <td>@Html.DisplayFor(modelItem=>item.Status)</td>
            <td class="text-center">
                <button type="button" class="btn btn-warning btn-xs detail" title="Detail" value="@item.Id"><i class="glyphicon glyphicon-eye-open"></i></button>
                <button type="button" class="btn btn-success btn-xs edit" title="Edit" value="@item.Id"><i class="glyphicon glyphicon-edit"></i></button>
                <button type="button" class="btn btn-danger btn-xs delete" title="Delete" value="@item.Id"><i class="glyphicon glyphicon-trash"></i></button>
            </td>
        </tr>
    }